### ISSUE TITLE
Docker issue?

### ISSUE THREAD

**Issue by jgentes** [resin-io/resin-preload#159]
Just ran into this, not sure what the problem is. Any thoughts?

```- Creating preloader container
/ Starting preloader container
\ Fetching application 966250

{ Error: Step 1/7 : FROM docker:17.10.0-ce-dind
 ---> 9769e0f3f9cb
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Running in 7b65e08afadd
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.2-256-g0319b040f4 [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.2-255-gdf44076119 [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8439 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/29) Installing libattr (2.4.47-r6)
(2/29) Installing libacl (2.2.52-r3)
(3/29) Installing coreutils (8.27-r0)
(4/29) Installing device-mapper-libs (2.02.168-r3)
(5/29) Installing libseccomp (2.3.2-r0)
(6/29) Installing docker (17.05.0-r0)
Executing docker-17.05.0-r0.pre-install
(7/29) Installing libmagic (5.32-r0)
(8/29) Installing file (5.32-r0)
(9/29) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(10/29) Installing ncurses-terminfo (6.0_p20171125-r0)
(11/29) Installing ncurses-libs (6.0_p20171125-r0)
(12/29) Installing readline (6.3.008-r5)
(13/29) Installing parted (3.2-r5)
(14/29) Installing libbz2 (1.0.6-r5)
(15/29) Installing expat (2.2.0-r1)
(16/29) Installing libffi (3.2.1-r3)
(17/29) Installing gdbm (1.12-r0)
(18/29) Installing sqlite-libs (3.20.1-r0)
(19/29) Installing python3 (3.6.1-r3)
(20/29) Installing libfdisk (2.28.2-r2)
(21/29) Installing libsmartcols (2.28.2-r2)
(22/29) Installing sfdisk (2.28.2-r2)
(23/29) Installing libgcc (6.3.0-r4)
(24/29) Installing popt (1.16-r6)
(25/29) Installing libstdc++ (6.3.0-r4)
(26/29) Installing sgdisk (1.0.1-r1)
(27/29) Installing libmount (2.28.2-r2)
(28/29) Installing findmnt (2.28.2-r2)
(29/29) Installing util-linux (2.28.2-r2)
Executing busybox-1.26.2-r7.trigger
OK: 186 MiB in 63 packages
Removing intermediate container 7b65e08afadd
 ---> 992f5a94a5b4
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> 5edf90a278fd
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Running in 0968e5bdd5d0
Collecting sh==1.12.14 (from -r /tmp/requirements.txt (line 1))
  Downloading sh-1.12.14-py2.py3-none-any.whl
Installing collected packages: sh
Successfully installed sh-1.12.14
Removing intermediate container 0968e5bdd5d0
 ---> c1183a955f0a
Step 5/7 : COPY ./src /usr/src/app
 ---> 3a3853ba9107
Step 6/7 : WORKDIR /usr/src/app
Removing intermediate container 7b9556c3daaa
 ---> 99de70e1ab1d
Step 7/7 : CMD /usr/src/app/preload.py
 ---> Running in 632a5bd7593c
Removing intermediate container 632a5bd7593c
 ---> 8aa0fd6ec328
Successfully built 8aa0fd6ec328
Successfully tagged resin/resin-preload:latest
    at container.wait.then (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\lib\preload.js:315:19)
    at tryCatcher (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-preload\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) code: 126 }```

**Comment by jgentes** [comment]
Looks like i'm getting a new error now:
```
PS C:\Dev\resin-SidekickDev> resin preload .\resin-SidekickDev-2.9.7+rev2-dev-v6.6.0.img --app 966250
Building Docker preloader image. [========================] 100%
| Checking that the image is a writable file
| Finding a free tcp port and getting resin settings
| Checking if the image is an edison zip archive
| Creating preloader container
| Cleaning up temporary files
{ Error: (HTTP code 400) unexpected - invalid mount config for type "bind": invalid mount path: 'C:/Dev/resin-SidekickDev/resin-SidekickDev-2.9.7+rev2-dev-v6.6.0.img' mount path must be absolute
    at C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-cli\node_modules\docker-modem\lib\modem.js:254:17
    at getCause (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-cli\node_modules\docker-modem\lib\modem.js:284:7)
    at Modem.buildPayload (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-cli\node_modules\docker-modem\lib\modem.js:253:5)
    at IncomingMessage.<anonymous> (C:\Users\jgent\AppData\Roaming\npm\node_modules\resin-cli\node_modules\docker-modem\lib\modem.js:229:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  reason: undefined,
  statusCode: 400,
  json: { message: 'invalid mount config for type "bind": invalid mount path: \'C:/Dev/resin-SidekickDev/resin-SidekickDev-2.9.7+rev2-dev-v6.6.0.img\' mount path must be absolute' } }
```
I'm using:
- resin-cli: not sure, would be nice if resin --version or resin --help provided this
- Windows 10 powershell
- docker 17.12.0-ce, build c97c6d6
- image is 2.9.7+rev2-dev-v6.6.0

**Comment by zvin** [comment]
@jgentes 
Could you please try with ?
`resin preload //c/Dev/resin-SidekickDev/resin-SidekickDev-2.9.7+rev2-dev-v6.6.0.img --app 966250`

**Comment by jgentes** [comment]
Sorry for the delay @zvin - here's what I'm trying:

    MINGW32 /c/Dev
    $ resin preload resin-SidekickPrd-2.12.3+rev1-v7.1.14/resin-SidekickPrd-2.12.3+rev1-v7.1.14.img  --app 978163 --splash-image /c/Dev/resin-logo.png

And that produces:
`Error: (HTTP code 400) unexpected - invalid mount config for type "bind": invalid mount path: 'C:/Dev/resin-logo.png' mount path must be absolute`

If I try double slashes `//c/Dev/resin-logo.png` it says `invalid mount config for type "bind": bind source path does not exist`

**Comment by jgentes** [comment]
I just installed ubuntu to get it working, no problems there :)
