### ISSUE TITLE
FS out of space error preloading app 

### ISSUE THREAD

**Issue by chenosaurus** [resin-io/resin-preload#172]
OS X 10.12.6
Docker version 17.12.0-ce, build c97c6d6

docker-preload crashes with the following error:

```
Davids-MacBook-Pro:edge-images dchen$ resin-preload --app xxxx --img ./resin-xxxx-2.12.5+rev6-v7.1.18.img --api-token "xxxx"
Building Docker preloader image. [========================] 100%

/ Creating preloader container
| Starting preloader container
- Fetching application 1031618
- Reading image information
| Resizing partitions and waiting for dockerd to start
Pulling 1 image [===================     ] 81%
- Cleaning up temporary files

{ Error: failed to register layer: Error processing tar file(exit status 1): write /root/workspace/edge1-app/node_modules/process-nextick-args/test.js: no space left on device
    at maybeWrapAsError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/bluebird/js/release/util.js:61:12)
    at /Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/bluebird/js/release/nodeback.js:38:50
    at onStreamError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/docker-modem/lib/modem.js:338:5)
    at Stream.onStreamEvent (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/docker-modem/lib/modem.js:326:14)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  cause: Error: failed to register layer: Error processing tar file(exit status 1): write /root/workspace/edge1-app/node_modules/process-nextick-args/test.js: no space left on device
    at maybeWrapAsError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/bluebird/js/release/util.js:61:12)
    at /Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/bluebird/js/release/nodeback.js:38:50
    at onStreamError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/docker-modem/lib/modem.js:338:5)
    at Stream.onStreamEvent (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/docker-modem/lib/modem.js:326:14)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-preload/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20),
  isOperational: true }
```

**Comment by chenosaurus** [comment]
nm, trying resin-cli
