### ISSUE TITLE
need to run npm install before running the script

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-preload#67]
Fails with this error if not run.
```
{ Error: Cannot find module 'command-join'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hobochild/Desktop/resin-preload/lib/preload.js:3:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by zvin** [comment]
@shaunmulligan this happens only if you clone the repo from github.
If you install it with `npm install --global resin-preload` (like in the README) you don't need to run `npm i`.

Do you want me to add instructions for installing from github ?

**Comment by shaunmulligan** [comment]
@zvin ah, that is a fair point. It might be worth putting that step in a "contributing" section for people that want to add to the project and will clone from github
