### ISSUE TITLE
Rare umount error.

### ISSUE THREAD

**Issue by zvin** [resin-io/resin-preload#89]
```
Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 427, in <module>
    main_preload()
  File "/usr/src/app/preload.py", line 413, in main_preload
    preload(IMAGE, additional_space, app_data)
  File "/usr/src/app/preload.py", line 357, in preload
    resize_fs_copy_splash_image_and_pull(image, app_data)
  File "/usr/src/app/preload.py", line 257, in resize_fs_copy_splash_image_and_pull
    docker_pull(docker_sock, app_data["imageId"])
  File "/usr/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/src/app/preload.py", line 92, in mount_context_manager
    umount(mountpoint)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_32: 

  RAN: /bin/umount /tmp/tmpm7kydi4e

  STDOUT:


  STDERR:
umount: /tmp/tmpm7kydi4e: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)

```

**Comment by zvin** [comment]
Fixed by #96 .
